name: project2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.7+4
  file_picker: ^5.0.0
  path_provider: ^2.0.10
  provider: ^6.1.2
  json_annotation: ^4.8.1
  flutter_dotenv: ^5.0.2
  googleapis: any
  googleapis_auth: any
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.6.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true



